### ISSUE TITLE
How to uninstall pear?

### ISSUE THREAD

**Issue by dipunm** [holepunchto/pear-docs#110]
Pear took ages to install and my computer ran out of battery.

I booted it and ran `pear` and it completed quickly, but I don't trust it.

How can I uninstall and re-install it? I tried `npm uninstall pear`, but after re-installing, it didn't attempt to re-initialise again.

Also, I would love to know what files it downloaded and where?

**Comment by Mysticswiss** [comment]
https://github.com/holepunchto/pear/blob/main/ARCHITECTURE.md    

![Screenshot from 2024-06-09 22-34-07](https://github.com/holepunchto/pear-docs/assets/156604323/d68bc0c7-5455-497f-a17e-5d802fb566bd)
