### ISSUE TITLE
Hyperswarm mention

### ISSUE THREAD

**Issue by d61b292b-2859-4ed6-8c7c-b7397ad8e351** [holepunchto/pear-docs#123]
Why is hyperswarm mentioned? It's not used in this guide

https://github.com/holepunchto/pear-docs/blob/ad3f757d8db0933d8b726af465548f48b4c63766/howto/connect-two-peers-by-key-with-hyperdht.md?plain=1#L4-L10

**Comment by HDegroote** [comment]
Thanks for the feedback! You're right, I PR'd a possible fix here: https://github.com/holepunchto/pear-docs/pull/137
