### ISSUE TITLE
Clarify sentence

### ISSUE THREAD

**Issue by d61b292b-2859-4ed6-8c7c-b7397ad8e351** [holepunchto/pear-docs#124]
https://github.com/holepunchto/pear-docs/blob/ad3f757d8db0933d8b726af465548f48b4c63766/building-blocks/hyperdht.md?plain=1#L114

Should probably be: 

> Servers can be run on normal home computers, as the DHT will UDP holepunch connections **that** are personal to users. 

?

**Comment by annadevile** [comment]
Fixed with PR #138
