### ISSUE TITLE
Hot reloading for index.html does not appear to work

### ISSUE THREAD

**Issue by d61b292b-2859-4ed6-8c7c-b7397ad8e351** [holepunchto/pear-docs#131]
https://github.com/holepunchto/pear-docs/blob/74a3e1a3f6b8faba77cc36b4cf053f5cb614d0ab/guide/starting-a-pear-desktop-project.md?plain=1#L36-L46

I did exactly that and nothing was updated

**Comment by annadevile** [comment]
hey! pear dev was deprecated, please see updated guide :)
